lexik_jwt_authentication:
  private_key_path: '%kernel.project_dir%/config/jwt/private.pem'
  public_key_path: '%kernel.project_dir%/config/jwt/public.pem'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: 86400

  token_extractors:
    authorization_header:
      enabled: false
    query_parameter:
      enabled: false
    cookie:
      enabled: true
      name: BEARER
