nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173', 'https://оранжевыйпомощник.рф', 'https://oranzhevyi-pomoshnik.ru']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_credentials: true
            allow_origin: ['http://localhost:5173', 'https://оранжевыйпомощник.рф', 'https://oranzhevyi-pomoshnik.ru']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
