security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: phoneNumber

    firewalls:
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login/check
                username_path: phoneNumber
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: App\Listener\CustomAuthenticationFailureHandler

        admin:
            pattern: ^/admin
            http_basic: ~
            provider: app_user_provider

